jwt:
  secret-key: 7J206rG0and07Iuc7YGs66a/7YKk7J6F64uI64uk7KGw7Ius7ZW07JW87ZW07JqU

admin:
  token: 7J206rG0YWRtaW50b2tlbuyeheuLiOuLpOydtOqyg+uPhOyhsOyLrO2VmOyEuOyalA

server:
  port: 9008

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/order_platform}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  #메일 설정
  mail:
    host: smtp.gmail.com
    port: 587 # SMTP 포트
    username: u05016@gmail.com
    password: mcto zlzy cvbd vfgo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org:
      springframework:
        cache: trace

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka}

  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
