server:
  port: 9000

spring:
  application:
    name: common

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/commerce}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
